/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package week13;

import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import koneksi.conek;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO
 */
public class Data_Matakuliah extends javax.swing.JFrame {

    /**
     * Creates new form Data_Matakuliah
     */
    public Data_Matakuliah() {
        initComponents();
        datatable();
        load_table();
        
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize  = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;  
        }
        if (frameSize.width  > screenSize.width) {
            frameSize.width  = screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) /2,
                         (screenSize.height - frameSize.height) /2);
    }
        private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID Distributor");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("No HP");
        
        String Cari = txt_Cari.getText();
        }
        public void datatable() {

        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode Matakuliah");
        tbl.addColumn("Matakuliah");
        tbl.addColumn("SKS");
        tbl.addColumn("SMT");
        tbl.addColumn("Jumlah Mahasiswa");
        table.setModel(tbl);
        try {
            Statement statement= (Statement)conek.getkoneksi().createStatement(); {
            ResultSet res=statement.executeQuery("select * from tb_matakuliah");
                tbl.addRow(new Object[]{
                    res.getString("kode_mk"),
                    res.getString("mk"),
                    res.getString("sks"),
                    res.getString("smt"),
                    res.getString("jml_mhs"),});
                table.setModel(tbl);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "berhasil");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtjml = new javax.swing.JTextField();
        txtkodemk = new javax.swing.JTextField();
        txtmk = new javax.swing.JTextField();
        txtsks = new javax.swing.JTextField();
        txtsmt = new javax.swing.JTextField();
        btnedit = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();
        btncari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_Cari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data_Matakuliah");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 29, 220, -1));

        jLabel3.setText("jml_mhs");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel5.setText("kode_mk");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel10.setText("mk");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel11.setText("sks");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel12.setText("smt");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        getContentPane().add(txtjml, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 280, -1));
        getContentPane().add(txtkodemk, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 280, -1));
        getContentPane().add(txtmk, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 280, -1));
        getContentPane().add(txtsks, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 280, -1));
        getContentPane().add(txtsmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 280, -1));

        btnedit.setText("edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 80, -1));

        btnsimpan.setText("simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        btnhapus.setText("hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 80, -1));

        btnkeluar.setText("keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        btncetak.setText("cetak");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });
        getContentPane().add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 70, -1));

        btncari.setText("cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        getContentPane().add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 70, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 370, 190));

        jLabel4.setText("cari");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));
        getContentPane().add(txt_Cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        // TODO add your handling code here:
        try {
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("report_matakuliah.jasper"), null, conek.getkoneksi());
        JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_btncetakActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        txtkodemk.setText("");
        txtmk.setText("");
        txtsks.setText("");
        txtsmt.setText("");
        txtjml.setText("");
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        String kode_mk = txtkodemk.getText();
        try {
            String statement = "DELETE FROM tb_matakuliah where kode_mk = ?";
            PreparedStatement pst = conek.getkoneksi().prepareStatement(statement);
            pst.setString(1, kode_mk);
            pst.execute();
            txtkodemk.setText("");
            txtmk.setText("");
            txtsks.setText("");
            txtsmt.setText("");
            txtjml.setText("");
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
        } catch (SQLException | NumberFormatException | HeadlessException t) {
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
            System.out.println(t.getMessage());
        }
        datatable();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String kode_mk = txtkodemk.getText();
        String mk = txtmk.getText();
        String sks = txtsks.getText();
        String smt = txtsmt.getText();
        String jml_mhs = txtjml.getText();
        
        try {
            // statement / perintah
            String statement = "INSERT INTO tb_matakuliah (kode_mk, mk, sks, smt, jml_mhs) "
                    + "VALUES(?,?,?,?,?)";
            PreparedStatement pst = conek.getkoneksi().prepareStatement(statement);
            pst.setString(1, kode_mk);
            pst.setString(2, mk);
            pst.setString(3, sks);
            pst.setString(4, smt);
            pst.setString(5, jml_mhs);
            
            pst.execute();
            JOptionPane.showMessageDialog(this, "Tambah data matakuliah berhasil!");
            datatable();
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Tambah data matakuliah gagal!");
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        load_table();
    }//GEN-LAST:event_btncariActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Matakuliah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_Cari;
    private javax.swing.JTextField txtjml;
    private javax.swing.JTextField txtkodemk;
    private javax.swing.JTextField txtmk;
    private javax.swing.JTextField txtsks;
    private javax.swing.JTextField txtsmt;
    // End of variables declaration//GEN-END:variables
}
